enum coal_enum_e {
    //TRUE,
    //FALSE,
    NONE,
    /* 2.7. AL Errors */
    /* Table 2.2: Error Conditions */
    NO_ERROR,
    INVALID_NAME,
    INVALID_ENUM,
    INVALID_VALUE,
    INVALID_OPERATION,
    OUT_OF_MEMORY,

    /* 3.1.1. Simple Queries */
    /* Table 3.1: Numerical Query Definitions */
    DOPPLER_FACTOR,
    SPEED_OF_SOUND,
    DISTANCE_MODEL,
    /* Table 3.2: String Query Definitions */
    VERSION,
    RENDERER,
    VENDOR,
    EXTENSIONS,
    /* 3.4. Attenuation By Distance */
    INVERSE_DISTANCE,
    INVERSE_DISTANCE_CLAMPED,
    LINEAR_DISTANCE,
    LINEAR_DISTANCE_CLAMPED,
    EXPONENT_DISTANCE,
    EXPONENT_DISTANCE_CLAMPED,

    /* 3.4.1. Inverse Distance Rolloff Model */
    // See below


    /* 4.1. Basic Listener and Source Attributes */
    POSITION,
    VELOCITY,
    GAIN,
    ORIENTATION,
    /* 4.3.2. Source Attributes */
    /* Source Positioning */
    SOURCE_RELATIVE,
    /* Source Type */
    SOURCE_TYPE,
    UNDETERMINED, /* source type */
    STATIC, /* source type */
    STREAMING, /* source type */
    /* Buffer Looping */
    LOOPING,
    /* Current Buffer */
    BUFFER,
    /* Queue State Queries */
    BUFFERS_QUEUED,
    BUFFERS_PROCESSED,
    /* Bounds on Gain */
    MIN_GAIN,
    MAX_GAIN,
    /* Distance Model Attributes */
    REFERENCE_DISTANCE,
    ROLLOFF_FACTOR,
    MAX_DISTANCE,
    /* Frequency Shift by Pitch */
    PITCH,
    /* Direction and Cone */
    DIRECTION,
    CONE_INNER_ANGLE,
    CONE_OUTER_ANGLE,
    CONE_OUTER_GAIN,
    /* Offset */
    SEC_OFFSET,
    SAMPLE_OFFSET,
    BYTE_OFFSET,
    /* 5.3.1. Buffer Attributes */
    FREQUENCY,
    SIZE,
    BITS,
    CHANNELS,
    /* 5.3.4. Specifying Buffer Content */
    FORMAT_MONO8,
    FORMAT_MONO16,
    FORMAT_STEREO8,
    FORMAT_STEREO16,

    /* Effects Extension (Standard + EAX) */
    /* Auxiliary Effect Slot Object */
    EFFECTSLOT_EFFECT,
    EFFECTSLOT_GAIN,
    EFFECTSLOT_AUXILIARY_SEND_AUTO,
    /* Effect Object */
    EFFECT_TYPE,
    /* AL_EFFECT_EAXREVERB */
    EAXREVERB_DENSITY,
    EAXREVERB_DIFFUSION,
    EAXREVERB_GAIN,
    EAXREVERB_GAINHF,
    EAXREVERB_GAINLF,
    EAXREVERB_DECAY_TIME,
    EAXREVERB_DECAY_HFRATIO,
    EAXREVERB_DECAY_LFRATIO,
    EAXREVERB_REFLECTIONS_GAIN,
    EAXREVERB_REFLECTIONS_DELAY,
    EAXREVERB_REFLECTIONS_PAN,
    EAXREVERB_LATE_REVERB_GAIN,
    EAXREVERB_LATE_REVERB_DELAY,
    EAXREVERB_LATE_REVERB_PAN,
    EAXREVERB_ECHO_TIME,
    EAXREVERB_ECHO_DEPTH,
    EAXREVERB_MODULATION_TIME,
    EAXREVERB_MODULATION_DEPTH,
    EAXREVERB_AIR_ABSORPTION_GAINHF,
    EAXREVERB_HFREFERENCE,
    EAXREVERB_LFREFERENCE,
    EAXREVERB_ROOM_ROLLOFF_FACTOR,
    EAXREVERB_DECAYHF_LIMIT,
    /* AL_EFFECT_REVERB */
    REVERB_DENSITY,
    REVERB_DIFFUSION,
    REVERB_GAIN,
    REVERB_GAINHF,
    REVERB_DECAY_TIME,
    REVERB_DECAY_HFRATIO,
    REVERB_REFLECTIONS_GAIN,
    REVERB_REFLECTIONS_DELAY,
    REVERB_LATE_REVERB_GAIN,
    REVERB_LATE_REVERB_DELAY,
    REVERB_AIR_ABSORPTION_GAINHF,
    REVERB_ROOM_ROLLOFF_FACTOR,
    REVERB_DECAY_HFLIMIT,
    /* AL_EFFECT_CHORUS */
    CHORUS_WAVEFORM,
    // CHORUS_WAVEFORM_SINUSOID = 0
    // CHORUS_WAVEFORM_TRIANGLE = 1
    CHORUS_PHASE,
    CHORUS_RATE,
    CHORUS_DEPTH,
    CHORUS_FEEDBACK,
    CHORUS_DELAY,
    /* AL_EFFECT_DISTORTION */
    DISTORTION_EDGE,
    DISTORTION_GAIN,
    DISTORTION_LOWPASS_CUTOFF,
    DISTORTION_EQCENTER,
    DISTORTION_EQBANDWIDTH,
    /* AL_EFFECT_ECHO */
    ECHO_DELAY,
    ECHO_LRDELAY,
    ECHO_DAMPING,
    ECHO_FEEDBACK,
    ECHO_SPREAD,
    /* AL_EFFECT_FLANGER */
    FLANGER_WAVEFORM,
    // FLANGER_WAVEFORM_SINUSOID = 0
    // FLANGER_WAVEFORM_TRIANGLE = 1
    FLANGER_PHASE,
    FLANGER_RATE,
    FLANGER_DEPTH,
    FLANGER_FEEDBACK,
    FLANGER_DELAY,
    /* AL_EFFECT_FREQUENCY_SHIFTER */
    FREQUENCY_SHIFTER_FREQUENCY,
    FREQUENCY_SHIFTER_LEFT_DIRECTION,
    FREQUENCY_SHIFTER_RIGHT_DIRECTION,
    /* AL_EFFECT_VOCAL_MORPHER */
    VOCAL_MORPHER_PHONEMEA,
    VOCAL_MORPHER_PHONEMEB,
    VOCAL_MORPHER_PHONEMEA_COARSE_TUNING,
    VOCAL_MORPHER_PHONEMEB_COARSE_TUNING,
    VOCAL_MORPHER_WAVEFORM,
    VOCAL_MORPHER_RATE,
    /* AL_EFFECT_PITCH_SHIFTER */
    PITCH_SHIFTER_COARSE_TUNE,
    PITCH_SHIFTER_FINE_TUNE,
    /* AL_EFFECT_RING_MODULATOR */
    RING_MODULATOR_FREQUENCY,
    RING_MODULATOR_HIGHPASS_CUTOFF,
    RING_MODULATOR_WAVEFORM,
    /* AL_EFFECT_AUTOWAH */
    AUTOWAH_ATTACK_TIME,
    AUTOWAH_RELEASE_TIME,
    AUTOWAH_RESONANCE,
    AUTOWAH_PEAK_GAIN,
    /* AL_EFFECT_COMPRESSOR */
    COMPRESSOR_ONOFF,
    /* AL_EFFECT_EQUALIZER */
    EQUALIZER_LOW_GAIN,
    EQUALIZER_LOW_CUTOFF,
    EQUALIZER_MID1_GAIN,
    EQUALIZER_MID1_CENTER,
    EQUALIZER_MID1_WIDTH,
    EQUALIZER_MID2_GAIN,
    EQUALIZER_MID2_CENTER,
    EQUALIZER_MID2_WIDTH,
    EQUALIZER_HIGH_GAIN,
    EQUALIZER_HIGH_CUTOFF,
    /* AL_FILTER_LOWPASS */
    LOWPASS_GAIN,
    LOWPASS_GAINHF,
    /* AL_FILTER_HIGHPASS */
    HIGHPASS_GAIN,
    HIGHPASS_GAINHF,
    /* AL_FILTER_BANDPASS */
    BANDPASS_GAIN,
    BANDPASS_GAINLF,
    BANDPASS_GAINHF,
    /* Source Object Extensions */
    DIRECT_FILTER,
    AUXILIARY_SEND_FILTER,
    AIR_ABSORPTION_FACTOR,
    ROOM_ROLLOFF_FACTOR,
    CONE_OUTER_GAINHF,
    DIRECT_FILTER_GAINHF_AUTO,
    AUXILIARY_SEND_FILTER_GAIN_AUTO,
    AUXILIARY_SEND_FILTER_GAINHF_AUTO,
    /* Listener Object Extensions */
    METERS_PER_UNIT,










    COAL_ENUM_DUMMY = 0x7fffffff
};

enum coal_ctx_enum_e {
    CTX_FREQUENCY,
    CTX_REFRESH,
    CTX_SYNC,
    CTX_MONO_SOURCES,
    CTX_STEREO_SOURCES,
    CTX_NO_ERROR,
    CTX_INVALID_DEVICE,
    CTX_INVALID_CONTEXT,
    CTX_INVALID_ENUM,
    CTX_INVALID_VALUE,
    CTX_OUT_OF_MEMORY,
    CTX_DEFAULT_DEVICE_SPECIFIER,
    CTX_DEVICE_SPECIFIER,
    CTX_EXTENSIONS,
    CTX_CAPTURE_DEFAULT_DEVICE_SPECIFIER,
    CTX_CAPTURE_DEVICE_SPECIFIER,
    CTX_ATTRIBUTES_SIZE,
    CTX_ALL_ATTRIBUTES,
    CTX_MAJOR_VERSION,
    CTX_MINOR_VERSION,
    CTX_CAPTURE_SAMPLES,
    /* Effects Extension (Standard + EAX) */
    /* Context Object Extensions */
    CTX_EFX_MAJOR_VERSION,
    CTX_EFX_MINOR_VERSION,
    CTX_MAX_AUXILIARY_SENDS,

    COAL_CTX_ENUM_DUMMY = 0x7fffffff

};

enum coal_effect_type_e {
    EFFECT_NULL,
    EFFECT_EAXREVERB,
    EFFECT_REVERB,
    EFFECT_CHORUS,
    EFFECT_DISTORTION,
    EFFECT_ECHO,
    EFFECT_FLANGER,
    EFFECT_FREQUENCY_SHIFTER,
    EFFECT_VOCAL_MORPHER,
    EFFECT_PITCH_SHIFTER,
    EFFECT_RING_MODULATOR,
    EFFECT_AUTOWAH,
    EFFECT_COMPRESSOR,
    EFFECT_EQUALIZER,

    COAL_EFFECT_DUMMY = 0x7fffffff

};

enum coal_filter_type_e {
    FILTER_NULL,
    FILTER_LOWPASS,
    FILTER_HIGHPASS,
    FILTER_BANDPASS,

    COAL_FILTER_DUMMY = 0x7fffffff
};

enum coal_phoneme_e {
    VOCAL_MORPHER_PHONEME_A,
    VOCAL_MORPHER_PHONEME_E,
    VOCAL_MORPHER_PHONEME_I,
    VOCAL_MORPHER_PHONEME_O,
    VOCAL_MORPHER_PHONEME_U,
    VOCAL_MORPHER_PHONEME_AA,
    VOCAL_MORPHER_PHONEME_AE,
    VOCAL_MORPHER_PHONEME_AH,
    VOCAL_MORPHER_PHONEME_AO,
    VOCAL_MORPHER_PHONEME_EH,
    VOCAL_MORPHER_PHONEME_ER,
    VOCAL_MORPHER_PHONEME_IH,
    VOCAL_MORPHER_PHONEME_IY,
    VOCAL_MORPHER_PHONEME_UH,
    VOCAL_MORPHER_PHONEME_UW,
    VOCAL_MORPHER_PHONEME_B,
    VOCAL_MORPHER_PHONEME_D,
    VOCAL_MORPHER_PHONEME_F,
    VOCAL_MORPHER_PHONEME_G,
    VOCAL_MORPHER_PHONEME_J,
    VOCAL_MORPHER_PHONEME_K,
    VOCAL_MORPHER_PHONEME_L,
    VOCAL_MORPHER_PHONEME_M,
    VOCAL_MORPHER_PHONEME_N,
    VOCAL_MORPHER_PHONEME_P,
    VOCAL_MORPHER_PHONEME_R,
    VOCAL_MORPHER_PHONEME_S,
    VOCAL_MORPHER_PHONEME_T,
    VOCAL_MORPHER_PHONEME_V,
    VOCAL_MORPHER_PHONEME_Z,

    COAL_PHONEME_DUMMY = 0x7fffffff
};
